### ISSUE TITLE
admin_email validation error

### ISSUE THREAD

**Issue by jursonovicst** [mfinelli/puppet-nsd#2]
The validation regexp for $admin_email in manifests/zonefile.pp does allow fqdns only with exactly one dot! The "admin@example.domain.com" value will be considered as invalid, and catalog will not be fetched.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Admin email address is invalid. at /etc/puppet/modules/nsd/manifests/zonefile.pp:137 on node xxxxxx.xx.xxxxxxxxxxx.com
```

You may update your regexp accordingly:

```
136c136
<   unless $admin_email =~ /^[A-Za-z0-9]+@[a-z0-9]+\.[a-z]+$/ {

---
>   unless $admin_email =~ /^[A-Za-z0-9]+@([a-z0-9]+\.)+[a-z]+$/ {
```

**Comment by mfinelli** [comment]
Published in version [0.6.1](https://github.com/mfinelli/puppet-nsd/releases/tag/v0.6.1)
