### ISSUE TITLE
'include-options' not working in ::nsd::zonefile 

### ISSUE THREAD

**Issue by wschoot** [mfinelli/puppet-nsd#3]
As per docs, I tried using 'include-options' in a ::nsd::zonefile declaration, but got:

Error: Invalid parameter include-options on Nsd::Zonefile[example.org] at [ ... ]

I tried setting it to include_options instead of 'include-options' and it works now

**Comment by mfinelli** [comment]
Thanks for reporting. I will look into this as soon as possible, but am out of the country for the next two weeks. I'm glad that you got it working in the meantime.

**Comment by mfinelli** [comment]
This was just a typo in the documentation. I've committed a fix and will publish a new version when I return.
