### ISSUE TITLE
Error "All nameservers must end in a full stop."

### ISSUE THREAD

**Issue by wschoot** [mfinelli/puppet-nsd#4]
Hi,

Why would you enforce the policy "All nameservers must end in a full stop." ?
I prefer to put it into my zone without an absolute name but with a relative name like below, and nsd is perfectly happy serving it. Furthermore, it simplifies my zonefilecreation as I can use "ns1" and "ns2" as defaults for all my zones:

> @ IN SOA ns1.foo.nl. foo.bar.bar. ( 2016030700 14400 3600 1209600 300 )
> 
>  NS ns1
>  NS ns2
> 
>  MX 10 mail
>  MX 20 fallback
>  MX 30 mail

I would suggest dropping this policy if that works for you.

**Comment by mfinelli** [comment]
I do not have a good answer for why this policy is enforced. It's really just personal preference since I serve mostly zones from name servers that do not match and this helps me avoid stupid mistakes.

However, I see your use case and think it is probably more common, so I will go ahead and change it. Unfortunately, it will have to wait two weeks for me to return home.

**Comment by wschoot** [comment]
If your fix would be "just rip out that piece of code", I can do that
and submit a pull request. If you wanna do more fancy stuff, I'm just
gonna sit back and wait for you to get back ;-)

**Comment by mfinelli** [comment]
Probably the only other thing that I would do would be to update the test suite. I have been trying to think of a way to detect relative vs. non-relative but nothing comes to mind short of adding every TLD to the rule (and even that would have false positives...) which is quite dumb... So probably will just be rip out the code.

If you want to submit a pull request then feel free but please do it against the `develop` branch. However, I can't do a release as I don't have any puppet packages installed on my travel laptop, so you'll have to wait until I get back anyway so it might not be worth your time...

**Comment by mfinelli** [comment]
@wschoot this should be fixed in version 0.7.0.
